### ISSUE TITLE
RTM may disconnect after some time

### ISSUE THREAD

**Issue by reschouw** [reschouw/HomelabHelper#1]
Bot seems to disconnect from Slack after some time. Crashes with following error log:
```
Traceback (most recent call last):
  File "/home/ubuntu/homelabhelper/helper/lib/python3.5/site-packages/slackclient/server.py", line 255, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/home/ubuntu/homelabhelper/helper/lib/python3.5/site-packages/websocket/_core.py", line 300, in recv
    opcode, data = self.recv_data()
  File "/home/ubuntu/homelabhelper/helper/lib/python3.5/site-packages/websocket/_core.py", line 317, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/ubuntu/homelabhelper/helper/lib/python3.5/site-packages/websocket/_core.py", line 330, in recv_data_frame
    frame = self.recv_frame()
  File "/home/ubuntu/homelabhelper/helper/lib/python3.5/site-packages/websocket/_core.py", line 364, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/ubuntu/homelabhelper/helper/lib/python3.5/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/home/ubuntu/homelabhelper/helper/lib/python3.5/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/home/ubuntu/homelabhelper/helper/lib/python3.5/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/ubuntu/homelabhelper/helper/lib/python3.5/site-packages/websocket/_core.py", line 434, in _recv
    return recv(self.sock, bufsize)
  File "/home/ubuntu/homelabhelper/helper/lib/python3.5/site-packages/websocket/_socket.py", line 94, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "homelabhelper.py", line 134, in <module>
    command, channel = parse_bot_commands(slack_client.rtm_read(), require_mention)
  File "/home/ubuntu/homelabhelper/helper/lib/python3.5/site-packages/slackclient/client.py", line 125, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/home/ubuntu/homelabhelper/helper/lib/python3.5/site-packages/slackclient/server.py", line 272, in websocket_safe_read
    raise SlackConnectionError("Unable to send due to closed RTM websocket")
slackclient.server.SlackConnectionError: Unable to send due to closed RTM websocket
```

**Comment by reschouw** [comment]
May be resolved by adding `auto_reconnect=True` but needs additional testing

**Comment by reschouw** [comment]
Earlier fix seems to have done it.
